### ISSUE TITLE
Bitcode Support

### ISSUE THREAD

**Issue by juliand665** [prsolucoes/mobile-pdfium#7]
It would be great if you could figure out a way to enable bitcode support in the build process somehow—I'm not sure where to even start here, but you might have an idea.

**Comment by prsolucoes** [comment]
Hi,

It is already supported.

You can check using the command:

```
otool -arch armv7 -l libpdfium.a | grep __LLVM
otool -arch arm64 -l libpdfium.a | grep __LLVM
```

or

```
otool -arch armv7 -l libpdfium.a | grep bitcode
otool -arch arm64 -llibpdfium.a | grep bitcode
```

Bitcode is disabled on simulator, because simulator don't have support for it and pdfium disable bitcode internally when detect simulator compilation. Bitcode only for arm to apple generate custom code for devices.

On pdfium BUILD.gn you have:
```
  if (use_xcode_clang && enable_ios_bitcode && !use_ios_simulator) {
    if (is_debug) {
      common_flags += [ "-fembed-bitcode-marker" ]
    } else {
      common_flags += [ "-fembed-bitcode" ]
    }
  }
```

On my script it is enabled here:
https://github.com/prsolucoes/mobile-pdfium/blob/master/make.py#L380-L385

Thanks.

**Comment by prsolucoes** [comment]
Hi,

In your SimplePDFExample, add the library and change "Enable Bitcode" on two targets (SimplePDFKit and SimplePDFExample). See:

![image](https://user-images.githubusercontent.com/395096/70081816-ff1de780-15e7-11ea-836b-8a83cae4541c.png)

![image](https://user-images.githubusercontent.com/395096/70081834-05ac5f00-15e8-11ea-815f-2ebcddad8949.png)

It compile without problems. Tested here.

**Comment by juliand665** [comment]
Oh wow, you're right. I was being an idiot, haha—I had only tried to enable it on the application, not SimplePDFKit…

Thanks again for all this!
